export const a = [
  { title: '旺店通ERP', description: '旺店通助力企业管理转型升级，成就企业规模化发展，选择旺店通，管理更轻松' },
  { title: '白鲸-畅聊', description: 'Facebook mesenger/Whatsapp等多IM聚合聊天，并内置集成邮件/工单等功能' },
  {
    title: '17track',
    description: '全球物流查询平台，覆盖世界上大多数国家，提供功能先进的国际快递，邮政包裹查询跟踪服务'
  },
  { title: 'Klaviyo', description: '邮件、短信营销工具，支持自动化营销' },
  { title: '商品推荐', description: '向买家推送相关性的其它商品，提高您的站点转化' },
  { title: '车型管理', description: '按车型筛选匹配产品，买家通过车型快速定位产品' },
  { title: '弹窗推广', description: '多场景弹窗推广，集成邮件和折扣码促销，促进商品销售' },
  { title: 'lnstagram照片墙', description: '展示lnstagram帖子，吸引用户关注追随，增加商品转化率' },
  { title: '白鲸-归因助手', description: '比广告平台官方效果数据更快更准的广告效果报表，让您的测款省钱省心' },
  { title: '白鲸-飞邮', description: '来自星盘白鲸的邮件营销工具。为您提供稳定高效的EDM工具' },
  { title: '白鲸-畅聊', description: 'Facebook mesenger/Whatsapp等多IM聚合聊天，并内置集成邮件/工单等功能' },
  { title: '白鲸-行业洞察', description: '竞手站点流量数据；自然/付费关键词流量数据与机会发现；丰富的广告素材挖掘' },
  { title: '限时折扣', description: '选择商品进行限时营销活动，可加快商品出售' },
  { title: '推荐有礼', description: '让客户推荐好友进店铺，获取裂变流量' },
  { title: '组合销售', description: '商品以组合的形式展示给客户，提高转换率和销售额' },
  { title: '联盟营销', description: '发展网红成为店铺分销员，大幅提升店铺流量与销量' },
  { title: '满减活动', description: '设置自动的满减活动，支持阶梯和循环满减，提升店铺客单价' },
  { title: '尺码表', description: '提供自由灵活的商品尺码表编辑功能，高效地管理商品尺码信息' },
  { title: '商品亚马逊外链', description: '商品外链到亚马逊店铺，提高商品下单转化率' },
  { title: '白鲸-商品助手', description: '一键抓取同步Aliexpress/Amazon/1688的商品到星盘店铺' },
  { title: '马帮ERP', description: '为跨境卖家提供订单处理、商品库存管理、采购供应链管理' },
  { title: '普源ERP', description: '跨境电商ERP一站式云服务平台' },
  { title: 'iBuYu', description: '跨境电商ERP一站式云服务平台' },
  {
    title: '易仓ERP',
    description: '易仓科技开放平台为拥有开发能力的易仓科技商户和第三方开发者提供API接口形式的基础服务'
  },
  { title: '聚水潭ERP', description: '聚水潭跨境ERP—真正SaaS架构的电商ERP管理系统' },
  { title: 'sminerp', description: '泗勉公司自研ERP' },
  { title: '隐私设置', description: '让客户对隐私数据进行控制，让你的店铺更符合经营地隐私法规' },
  { title: '商品筛选', description: '自定义商品筛选器，帮助客户更快速筛选出合适的商品' },
  { title: '翻译', description: '店铺多语言翻译，更好的服务全球买家' },
  { title: '人群管理', description: '自定义人群圈选+丰富的预置人群，开展精准再营销' },
  { title: '商品定制', description: '用户进行商品定制，有效提高商品销量与用户粘性' },
  { title: '隐私设置', description: '让客户对隐私数据进行控制，让你的店铺更符合经营地隐私法规' },
  { title: '商品筛选', description: '自定义商品筛选器，帮助客户更快速筛选出合适的商品' },
  { title: '翻译', description: '店铺多语言翻译，更好的服务全球买家' },
  { title: '人群管理', description: '自定义人群圈选+丰富的预置人群，开展精准再营销' },
  { title: '商品定制', description: '用户进行商品定制，有效提高商品销量与用户粘性' },
  { title: '询盘', description: '提供B2B询盘解决方案' },
  { title: '小额批发', description: '分别设置商品的批发价格，使客户在购买一定数量的商品可享受更优惠的单价。' }
]
