export const site = {
  certification: {
    text: '资质准备',
    ability: {
      feature: [],
      operate: [
        {
          title: '海外企业主体申请',
          desc: '协助申请海外（多国家地区）企业主体',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '海外品牌商标注册',
          desc: '协助注册海外（多国家地区）品牌商标',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '收款账号申请',
          desc: 'PayPal/Stripe/LianLian等收款账号申请',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '域名准备',
          desc: '域名申请及解析',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  site: {
    text: '个性化建站',
    ability: {
      feature: [
        {
          title: '行业精选模版',
          desc: '主流行业模版全覆盖，丰富组件供选择',
          base: true,
          ultimate: true,
          enterprise: true,
        },

        {
          title: '个性定制模版',
          desc: '根据业务和品牌风格，量身订制专属模版',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '店铺装修',
          desc: '主题模版安装，支持多页面自定义装修配置',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '一页网店',
          desc: '快速搭建“轻”店铺，实现商品直达，一键下单',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '导购',
          desc: '导航管理/搜索/个性化推荐/商品筛选器',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '博客管理',
          desc: '支持富文本和多媒体的博客系统',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '极致多端体验',
          desc: '提供极佳的无线及PC购物体验',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '域名绑定',
          desc: '主子域名绑定，支持多域名指向',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '全托管建站',
          desc: '专业极致的全流程建站服务',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '网站信息结构优化',
          desc: '网站demo设计，导航/首页/footer等各项模块优化',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '站点视觉风格优化',
          desc: '网站整体风格和内容设计优化',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '品类结构优化',
          desc: '商品分类设置和优化',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '页面优化',
          desc: '页面视觉以及信息优化',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  product: {
    text: '商品管理',
    ability: {
      feature: [
        {
          title: '商品发布',
          desc: '商品发布，批量商品编辑和导入',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: 'SKU管理',
          desc: 'SKU属性及库存管理',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: 'SEO属性设置',
          desc: '面向SEO设置标题/页面描述/URL/ALT',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品分类管理',
          desc: '集合/标签/类目管理',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '评价管理',
          desc: '站内购买客户留评，第三方平台评价导入',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '爆款挖掘',
          desc: '根据行业趋势和竞品动态挖掘已有商品和行业内爆品',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品信息优化',
          desc: '商品标题/详情/图片/SEO信息优化',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品集结构制定',
          desc: '组织商品集结构并优化展示页面',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '标签分类',
          desc: '通过标签进行商品多维度管理',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  trading: {
    text: '交易达成',
    ability: {
      feature: [
        {
          title: '促销',
          desc: '折扣码/优惠券/满减/限时促销/免邮/组合售卖',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '运费模版',
          desc: '全球国家/地区范围运费配置，商品分区域售卖配置',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '支付/快捷支付/分期支付',
          desc: '主流卡支付/PayPal支付/各类分期支付集成，ApplePay/GooglePay/PayPalExpress快捷支付集成',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '订单管理',
          desc: '发货/退款/邮件通知',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '物流追踪',
          desc: '直达订单物流追踪',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '促销方案设计',
          desc: '根据目标国家营销日历，制定广告营销计划及站内营销活动',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '运费方案优化',
          desc: '分析商品成本结构制定运费策略',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '支付风控运营',
          desc: 'ChargeBack/Dispute跟进处理',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  brand: {
    text: '品牌策划',
    ability: {
      feature: [
        {
          title: '行业数据',
          desc: '同行业独立站（竞对）数据',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告关键词库',
          desc: '关键词数据搜索，关键词相关推荐',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告素材库',
          desc: '海量图片/文字/视频广告素材提供素材制作灵感',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '选品库',
          desc: '同行业GoogleShopping/Amazon选品库',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '行业调研',
          desc: '调研行业全球市场/区域市场数据/行业趋势等',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '商品卖点剖析',
          desc: '根据产品本身特性，行业市场情况，目标受众痛点剖析挖掘商品卖点',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '商品受众和场景分析',
          desc: '还原目标受众使用场景，进一步挖掘目标受众',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '竞对分析',
          desc: '行业竞对分析，挖掘机会市场，制定相应竞争策略',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '品牌定位',
          desc: '结合商品卖点/目标客群/竞对情况，进一步明确品牌定位',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '商品策略',
          desc: '结合现有产品线及目标客群消费习惯，梳理产品线结构，匹配不同的营销渠道和打法',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '定价策略',
          desc: '结合目标受众购买力/竞品定价，对营销/物流等各项成本核算，制定定价策略',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '目标市场策略',
          desc: '根据产品特性/竞对情况/目标受众区域分布，制定分阶段目标市场策略',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
    },
  },
  country: {
    text: '多国家市场',
    ability: {
      feature: [
        {
          title: '店铺多语言',
          desc: '多语言手动录入/自动翻译',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品多语言',
          desc: '商品信息多语言自动翻译',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多币种自动汇率',
          desc: '支持主流币种，实现准实时汇率更新，减少汇损',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多币种固定汇率',
          desc: '支持主流币种自定义固定汇率，不受市场汇率波动影响',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '本地支付方式集成',
          desc: '欧洲及其他地区本地支付方式接入',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '多国家差异化运营',
          desc: '制定多国家本地化运营策略，匹配当地用户习惯及文化',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '本地政策合规',
          desc: '提供目标国家和对应品类的特殊政策咨询及处理',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  analysis: {
    text: '数据分析',
    ability: {
      feature: [
        {
          title: '销售数据报表',
          desc: '销售额/订单数/客单价等销售数据报表查询',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '用户行为数据报表',
          desc: '访客数/加购率/结帐率/支付转化率等数据报表查询',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品指标数据报表',
          desc: '售卖件数/商品访问热度/商品加购次数等数据报表查询',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '全站数据分析',
          desc: '全站销量/用户/渠道等数据日常监控与分析',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '转化漏斗数据分析',
          desc: '流量漏斗监控与分析，异常情况监控，购物环节优化',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品数据分析',
          desc: '商品数据日常分析，潜力商品挖掘',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  save: {
    text: '基础、合规、安全',
    ability: {
      feature: [
        {
          title: 'GDPR/CCPA隐私管理',
          desc: '隐私条款内容编辑，Cookies分类设置',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: 'VAT计算/代收',
          desc: '税率及计算规则配置，支持商品含税价',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多员工账号',
          desc: '管理/新建/邀请店铺员工账号',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '操作日志',
          desc: '店铺操作行为记录',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '安全防护',
          desc: '防DDOS/CC/CSRF/XSS等攻击',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '加密证书',
          desc: 'SSL安全协议',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '数据备份',
          desc: '多数据库备份',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '全球CDN加速',
          desc: '遍布全球的CDN加速节点',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '全球多云多区域部署',
          desc: '主流国家市场本地化云服务部署，提供高性能/稳定的购物体验',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: 'VAT税务咨询',
          desc: '不同国家VAT政策咨询	',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '合规咨询及运营',
          desc: '不同国家合规策略制定及落实',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '系统监控及维护',
          desc: '7*24小时在线监控服务，保障系统可用性	',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  service: {
    text: '品牌生态服务',
    ability: {
      feature: [
        {
          title: '应用市场',
          desc: '可安装官方和第三方的应用',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '开放API',
          desc: '通过API调用与现有系统进行集成',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '支付服务商对接',
          desc: '对接PayPal/Stripe/LianLian/Payoneer等行业头部支付收款服务商',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '物流服务商对接',
          desc: '对接纵腾/4PX/燕文/菜鸟国际/顺丰国际等行业头部物流服务商',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: 'ERP服务商对接',
          desc: '对接旺店通/店小秘等行业头部跨境ERP服务商',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '品牌服务商对接',
          desc: '对接优质品牌咨询公司',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '税务服务商对接',
          desc: '对接VAT税务咨询及服务提供商',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '内容服务商对接',
          desc: '对接专业素材/内容服务商',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  launch: {
    text: '投放',
    ability: {
      feature: [
        {
          title: '创意中心',
          desc: '图片/视频/文字等广告素材管理',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '商品Catalog同步',
          desc: '商品同步至GMC/Facebook Catalog',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '人群圈选',
          desc: '人群基础特征/偏好条件圈选',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多广告渠道集成',
          desc: 'Google/Facebook/Instagram/TikTok等广告渠道系统集成',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '自动化投放',
          desc: '出价/人群投放/地域投放/定时投放自动化',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告数据归因',
          desc: '基于一方数据的全链路广告归因，打通广告渠道API进行数据上传',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '全域广告数据看板',
          desc: '多广告渠道API打通，广告数据回传，统一广告数据视图',
          base: true,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '广告开户',
          desc: 'Google/Facebook/TikTok/Bing/Twitter/Snapchat等广告渠道开户',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多广告渠道投放策略',
          desc: '基于行业竞品推广监测及渠道特性，制定关键词/人群/素材等维度的广告投放策略',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告结构搭建',
          desc: '制定Google/Facebook/Instagram/TikTok等推广渠道的广告结构',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '人群标签管理',
          desc: '一站式管理人群标签，沉淀人群数据资产',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '再营销广告创建',
          desc: '再营销人群分层和圈选，跨渠道再营销广告搭建',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告素材优化',
          desc: '基于投放数据以及竞品热门素材，优化广告素材',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '广告数据分析及优化',
          desc: '对广告数据持续分析，对素材/人群定位/转化节点进行优化',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
  useOperate: {
    text: '用户运营',
    ability: {
      feature: [
        {
          title: '顾客管理',
          desc: '邮件订阅/潜客/购买客户打标及管理/一方顾客数据批量导入/自动匹配已有人群标签',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '多渠道顾客数据匹配',
          desc: '全链路匹配广告渠道用户/人群数据，精准定义客户画像，丰富顾客数据指标',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '多消息渠道触达',
          desc: '邮件/WhatsApp/Messenger/Apple Business Chat等高频场景触达',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '弃单召回',
          desc: '通过自动邮件进行弃单召回',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '心愿单',
          desc: '买家心愿单管理',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '会员忠诚计划',
          desc: '会员等级/权益/服务/积分/专享价',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '邮件营销',
          desc: '	设置邮件营销节奏和内容，并根据数据反馈进行优化调整',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '弃单邮件设置并优化',
          desc: '设计弃单召回节奏和内容，并根据数据反馈进行优化调整',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '私域运营',
          desc: 'WhatsApp/Messenger/Apple Business Chat等多渠道一站式运营策略',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '会员分层运营',
          desc: '构建会员体系，匹配会员权益并制定营销策略',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
    },
  },
  socialOperate: {
    text: '社媒运营',
    ability: {
      feature: [
        {
          title: '多社媒平台一站式管理',
          desc: '社媒内容查看/编辑，互动数据报告',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '帖子排期发布',
          desc: '内容日历排期表，定时发帖设置',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '热门话题推荐和管理',
          desc: '热门话题数据查询，根据帖子内容智能推荐相关话题',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '自动帖子生成',
          desc: '可设定自动内容生成规则，单品/商品集自动帖子生成',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: '社媒账号基础设置',
          desc: '	制定账号Profile/Story/图片/视频内容框架',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '内容设计与排期',
          desc: '根据品牌/用户/行业趋势等，提供日常内容设计与排期',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '相关热门话题挖掘',
          desc: '挖掘潜力涨粉话题，提高社媒账号自然曝光率',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '品牌相关标签积累',
          desc: '推动红人合作/粉丝活动，积累品牌标签',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '社群运营',
          desc: '私域社群运营/社群生态培育',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '粉丝增长运营',
          desc: '制定粉丝增长目标，多渠道营销活动实施',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
    },
  },
  marketing: {
    text: '红人营销',
    ability: {
      feature: [
        {
          title: '网红库',
          desc: '分地区/平台网红数据查询',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '任务平台',
          desc: '推广/带货任务分发和管理',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '结算平台',
          desc: '网红推广/带货佣金结算',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: 'MCN对接',
          desc: '国内外知名MCN机构/海外独立红人对接',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '红人匹配',
          desc: '分析网红及其粉丝画像，结合转化指标匹配优质红人',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '红人运营',
          desc: '	制定红人运营策略/衡量指标/权益/任务要求/红人效果数据追踪',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
    },
  },
  seo: {
    text: 'SEO ',
    ability: {
      feature: [
        {
          title: '站点地图',
          desc: '面向搜索引擎的sitemap自动生成和更新',
          base: true,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '站点报告',
          desc: '站点SEO评测检查和报告生成',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '关键词管理',
          desc: '行业SEO关键词指标数据，管理相关关键词',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
      operate: [
        {
          title: 'OnPage优化',
          desc: '页面SEO结构/内容优化',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '站点深度优化',
          desc: '拓展机会关键词/优化核心关键词排名',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '反链建设',
          desc: '分阶段实施不同层级反向链接',
          base: false,
          ultimate: false,
          enterprise: true,
        },
        {
          title: '数据报告',
          desc: '提供排名及自然流量监测报告',
          base: false,
          ultimate: false,
          enterprise: true,
        },
      ],
    },
  },
  additional: {
    text: '附加服务',
    ability: {
      feature: [],
      operate: [
        {
          title: 'SOP培训',
          desc: '指导搭建运营团队/运营SOP',
          base: true,
          ultimate: false,
          enterprise: false,
        },
        {
          title: '广告投放策略培训',
          desc: '每个季度培训一次广告投放策略',
          base: true,
          ultimate: false,
          enterprise: false,
        },
        {
          title: 'SOP搭建',
          desc: '搭建的全链路运营SOP(星盘运营团队与客户运营团队相协作)',
          base: false,
          ultimate: true,
          enterprise: true,
        },
        {
          title: '月度运营报告',
          desc: '产出全链路月度运营报告',
          base: false,
          ultimate: true,
          enterprise: true,
        },
      ],
    },
  },
}
