import { GetServerSideProps } from 'next'
import { GetServerSidePropsContext } from 'next/types'

const Sitemap = () => null

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const res = ctx.res
  if (res) {
    try {
      res.setHeader('Content-Type', 'application/xml')
      res.write(`<?xml version="1.0" encoding="UTF-8"?>
      <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
        <!-- Generated by Web-Site-Map.com -->
        <url>
            <loc>https://www.ishopastro.com/</loc>
            <changefreq>monthly</changefreq>
            <priority>1.00</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/dtc</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/b2b</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/beluga</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/solutions</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/about</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/partners</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/product</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/privacy</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
        <url>
            <loc>https://www.ishopastro.com/agreement</loc>
            <changefreq>monthly</changefreq>
            <priority>0.85</priority>
        </url>
      </urlset>`)
    } catch (err) {
      res.statusCode = 404
      res.write("Sorry can't find that!")
    } finally {
      res.end()
    }
    return { props: {} }
  } else {
    return { props: {} }
  }
}

export default Sitemap
